name: Deploy site on Azure storage static website

on:
  push:
    branches:
      - main

  workflow_dispatch:


permissions:
  id-token: 'write'

env:
    ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
    ARM_TENANT_ID: ${{ secrets.TENANT_ID}}
    ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID}}
    WORKING_DIRECTORY: './src'
    AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }} # varies
    AZURE_ACCOUNT_NAME:  sacloudpsyh # varies
    
  


jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Check presence of index.html
        run: |
          if [ ! -f "${{env.WORKING_DIRECTORY}}/index.html"]; then
            echo "Error: index.html is missing"
            exit 1
          fi
      
      - name: Azure CLI login
        uses: azure/login@v2
        with:
          client-id: ${{env.ARM_CLIENT_ID}}
          tenant-id: ${{env.ARM_TENANT_ID}}
          subscription-id: ${{env.ARM_SUBSCRIPTION_ID}}

      - name: upload files to blob storage
        run: |
          az storage blob upload-batch \
          --account-name ${{ env.AZURE_ACCOUNT_NAME }} \
          --destination '$web' \
          --source ${{ env.WORKING_DIRECTORY }} \

